blank_issues_enabled: false
contact_links:
  - name: Link preview
    url: https://github.com/flyerhq/react-native-link-preview/issues/new
    about: Use this to report link preview issues.
  - name: Chat UI
    url: https://github.com/flyerhq/react-native-chat-ui/issues/new/choose
    about: Use this to report chat UI issues.
